import React, { useState, useEffect } from 'react';
import { registerAthlete, generateDraws, fetchAthletes, updateEventDetails, createCategory } from '../api';
import { UserPlus, RefreshCw, Users, ShieldAlert, Settings, Save, ToggleLeft, ToggleRight, MapPin } from 'lucide-react';

const AZ_VENUES = [
  { name: "İsmayıllı Olimpiya İdman Kompleksi", query: "İsmayıllı Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Bakı İdman Sarayı", query: "Bakı İdman Sarayı, Baku, Azerbaijan" },
  { name: "Bakı Kristal Zalı", query: "Baku Crystal Hall, Baku, Azerbaijan" },
  { name: "Milli Gimnastika Arenası", query: "National Gymnastics Arena, Baku, Azerbaijan" },
  { name: "Heydər Əliyev adına İdman Konsert Kompleksi", query: "Heydər Əliyev adına İdman Konsert Kompleksi, Baku, Azerbaijan" },
  { name: "Quba Olimpiya İdman Kompleksi", query: "Quba Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Şəki Olimpiya İdman Kompleksi", query: "Şəki Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Gəncə Olimpiya İdman Kompleksi", query: "Gəncə Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Sumqayıt Olimpiya İdman Kompleksi", query: "Sumqayıt Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Lənkəran Olimpiya İdman Kompleksi", query: "Lənkəran Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Şamaxı Olimpiya İdman Kompleksi", query: "Şamaxı Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Göygöl Olimpiya İdman Kompleksi", query: "Göygöl Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Masallı Olimpiya İdman Kompleksi", query: "Masallı Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Abşeron Olimpiya İdman Kompleksi", query: "Abşeron Olimpiya İdman Kompleksi, Xırdalan, Azerbaijan" },
  { name: "Şəmkir Olimpiya İdman Kompleksi", query: "Şəmkir Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Tovuz Olimpiya İdman Kompleksi", query: "Tovuz Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Qazax Olimpiya İdman Kompleksi", query: "Qazax Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Ağdam Olimpiya İdman Kompleksi", query: "Ağdam Olimpiya İdman Kompleksi, Quzanlı, Azerbaijan" },
  { name: "Bərdə Olimpiya İdman Kompleksi", query: "Bərdə Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Naxçıvan Olimpiya İdman Kompleksi", query: "Naxçıvan Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Salyan Olimpiya İdman Kompleksi", query: "Salyan Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Biləsuvar Olimpiya İdman Kompleksi", query: "Biləsuvar Olimpiya İdman Kompleksi, Azerbaijan" },
  { name: "Cəlilabad Olimpiya İdman Kompleksi", query: "Cəlilabad Olimpiya İdman Kompleksi, Azerbaijan" }
];

export default function Admin({ 
  event, 
  categories, 
  selectedCategoryId, 
  setSelectedCategoryId, 
  eventId, 
  onRefreshData,
  onRefreshEvent 
}) {
  // Event settings form states
  const [eventTitle, setEventTitle] = useState(event?.title || '');
  const [eventDate, setEventDate] = useState(event?.date || '');
  const [eventLoc, setEventLoc] = useState(event?.location || '');
  const [eventLocUrl, setEventLocUrl] = useState(event?.locationUrl || '');
  const [eventDesc, setEventDesc] = useState(event?.description || '');
  const [regStatus, setRegStatus] = useState(event?.registrationStatus || 'closed');
  const [eventSaveLoading, setEventSaveLoading] = useState(false);

  // Athlete Registration form state
  const [name, setName] = useState('');
  const [club, setClub] = useState('');
  const [country, setCountry] = useState('AZE');
  const [targetCategoryId, setTargetCategoryId] = useState('');
  const [regLoading, setRegLoading] = useState(false);

  // Athlete list state
  const [athletes, setAthletes] = useState([]);
  const [athletesLoading, setAthletesLoading] = useState(false);

  // Category creation state
  const [catName, setCatName] = useState('');
  const [catAge, setCatAge] = useState('');
  const [catWeight, setCatWeight] = useState('');
  const [catGender, setCatGender] = useState('Oğlanlar');
  const [catType, setCatType] = useState('kumite');
  const [catLoading, setCatLoading] = useState(false);

  // Sync event inputs when event object changes
  useEffect(() => {
    if (event) {
      setEventTitle(event.title);
      setEventDate(event.date);
      setEventLoc(event.location);
      setEventLocUrl(event.locationUrl);
      setEventDesc(event.description);
      setRegStatus(event.registrationStatus || 'closed');
    }
  }, [event]);

  const handleVenueChange = (val) => {
    setEventLoc(val);
    
    // Check if the current URL is empty, or is an auto-generated search URL
    const isAutogenerated = !eventLocUrl || eventLocUrl.startsWith('https://www.google.com/maps/search/?api=1');
    
    if (isAutogenerated) {
      const found = AZ_VENUES.find(v => v.name.toLowerCase() === val.trim().toLowerCase());
      if (found) {
        setEventLocUrl(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(found.query)}`);
      } else if (val.trim()) {
        setEventLocUrl(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(val.trim() + ", Azerbaijan")}`);
      } else {
        setEventLocUrl('');
      }
    }
  };

  useEffect(() => {
    if (selectedCategoryId) {
      loadAthletes();
    }
  }, [selectedCategoryId]);

  async function loadAthletes() {
    setAthletesLoading(true);
    try {
      const data = await fetchAthletes(selectedCategoryId);
      setAthletes(data);
    } catch (err) {
      console.error(err);
    } finally {
      setAthletesLoading(false);
    }
  }

  async function handleUpdateEvent(e) {
    e.preventDefault();
    if (!eventTitle.trim() || !eventLoc.trim()) {
      alert('Başlıq və Məkan boş qala bilməz.');
      return;
    }

    setEventSaveLoading(true);
    try {
      await updateEventDetails(eventId, {
        title: eventTitle.trim(),
        date: eventDate,
        location: eventLoc.trim(),
        locationUrl: eventLocUrl.trim(),
        description: eventDesc.trim(),
        registrationStatus: regStatus
      });
      alert('Turnir parametrləri uğurla yadda saxlanıldı!');
      onRefreshEvent();
    } catch (err) {
      alert('Yadda saxlayarkən xəta baş verdi: ' + err.message);
    } finally {
      setEventSaveLoading(false);
    }
  }

  async function handleRegister(e) {
    e.preventDefault();
    if (!name.trim() || !club.trim() || !targetCategoryId) {
      alert('Zəhmət olmasa bütün sahələri doldurun.');
      return;
    }

    setRegLoading(true);
    try {
      await registerAthlete(targetCategoryId, {
        name: name.trim().toUpperCase(),
        club: club.trim(),
        country: country.trim().toUpperCase()
      });
      
      setName('');
      setClub('');
      alert('İdmançı uğurla qeydiyyatdan keçdi.');
      
      // Reload list if we registered for current viewing category
      if (targetCategoryId === selectedCategoryId) {
        loadAthletes();
      }
      onRefreshData();
    } catch (err) {
      alert('Xəta baş verdi: ' + err.message);
    } finally {
      setRegLoading(false);
    }
  }

  async function handleAddCategory(e) {
    e.preventDefault();
    if (!catName.trim() || !catAge.trim() || !catWeight.trim()) {
      alert('Zəhmət olmasa bütün sahələri doldurun.');
      return;
    }
    setCatLoading(true);
    try {
      await createCategory(eventId, {
        name: catName.trim(),
        age: catAge.trim(),
        weight: catWeight.trim(),
        gender: catGender,
        type: catType
      });
      alert('Yeni kateqoriya uğurla əlavə edildi!');
      setCatName('');
      setCatAge('');
      setCatWeight('');
      onRefreshEvent();
    } catch (err) {
      alert('Xəta baş verdi: ' + err.message);
    } finally {
      setCatLoading(false);
    }
  }

  async function handleGenerateBrackets() {
    if (!selectedCategoryId) {
      alert('Zəhmət olmasa kateqoriya seçin.');
      return;
    }

    if (!confirm('Bu kateqoriya üçün püşkatmanı yenidən yaratmaq istədiyinizdən əminsiniz? Bütün mövcud matç xalları sıfırlanacaq.')) {
      return;
    }

    try {
      await generateDraws(eventId, selectedCategoryId);
      alert('Püşkatma uğurla yenidən yaradıldı və byes/seeding hesablandı.');
      onRefreshData();
    } catch (err) {
      alert('Xəta baş verdi: ' + err.message);
    }
  }

  return (
    <div className="space-y-6">
      
      {/* 3-Column Admin Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        
        {/* Column 1: Event Configuration */}
        <div className="bg-white border border-gray-100 rounded-xl p-5 shadow-xs space-y-4 h-fit">
          <div className="flex items-center gap-2 border-b border-gray-50 pb-3">
            <Settings className="w-5 h-5 text-gray-500" />
            <h2 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider">Turnir Parametrləri</h2>
          </div>

          <form onSubmit={handleUpdateEvent} className="space-y-4">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Turnirin Adı</label>
              <input
                type="text"
                required
                value={eventTitle}
                onChange={(e) => setEventTitle(e.target.value)}
                placeholder="Məs. Fudokan karate üzrə turnir (2-ci liqa)"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900 font-medium"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Məkan Adı</label>
                <input
                  type="text"
                  required
                  list="az-venues-list"
                  value={eventLoc}
                  onChange={(e) => handleVenueChange(e.target.value)}
                  placeholder="Məs. İsmayıllı Olimpiya İdman Kompleksi"
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
                />
                <datalist id="az-venues-list">
                  {AZ_VENUES.map((venue, idx) => (
                    <option key={idx} value={venue.name} />
                  ))}
                </datalist>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Tarix</label>
                <input
                  type="date"
                  required
                  value={eventDate}
                  onChange={(e) => setEventDate(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
                />
              </div>
            </div>

            <div>
              <div className="flex justify-between items-center mb-1.5">
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider">Google Maps Linki</label>
                {eventLoc.trim() && (
                  <a
                    href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(eventLoc.trim() + ", Azerbaijan")}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[10px] text-gray-500 hover:text-gray-950 font-bold transition-colors flex items-center gap-0.5"
                    title="Google Maps-də axtar"
                  >
                    <MapPin className="w-3 h-3 text-red-500" />
                    <span>Xəritədə axtar ↗</span>
                  </a>
                )}
              </div>
              <input
                type="url"
                value={eventLocUrl}
                onChange={(e) => setEventLocUrl(e.target.value)}
                placeholder="Google Maps URL"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Turnir Haqqında</label>
              <textarea
                value={eventDesc}
                onChange={(e) => setEventDesc(e.target.value)}
                rows={3}
                placeholder="Məlumat və qaydalar..."
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900 leading-relaxed"
              ></textarea>
            </div>

            {/* Registration toggle */}
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-100">
              <div>
                <p className="text-xs font-bold text-gray-800">Qeydiyyat Statusu</p>
                <p className="text-[9px] text-gray-400 mt-0.5">Qeydiyyatın açıq və ya qapalı olması</p>
              </div>
              <button
                type="button"
                onClick={() => setRegStatus(regStatus === 'open' ? 'closed' : 'open')}
                className="text-gray-600 focus:outline-hidden cursor-pointer hover:text-gray-900"
              >
                {regStatus === 'open' ? (
                  <div className="flex items-center gap-1 text-emerald-600 font-bold text-xs">
                    <span>AÇIQ</span>
                    <ToggleRight className="w-8 h-8" />
                  </div>
                ) : (
                  <div className="flex items-center gap-1 text-red-500 font-bold text-xs">
                    <span>BAĞLI</span>
                    <ToggleLeft className="w-8 h-8" />
                  </div>
                )}
              </button>
            </div>

            <button
              type="submit"
              disabled={eventSaveLoading}
              className="w-full py-2.5 bg-gray-900 hover:bg-gray-800 text-white rounded-lg text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer flex items-center justify-center gap-1.5"
            >
              <Save className="w-3.5 h-3.5" /> Parametrləri Yadda Saxla
            </button>
          </form>
        </div>

        {/* Column 2: Roster & Seeding */}
        <div className="bg-white border border-gray-100 rounded-xl p-5 shadow-xs space-y-4 h-fit">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-gray-50 pb-3">
            <div className="flex items-center gap-2">
              <Users className="w-5 h-5 text-gray-500" />
              <h2 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider">İştirakçı Rosteri</h2>
            </div>
            
            <select
              value={selectedCategoryId || ''}
              onChange={(e) => setSelectedCategoryId(e.target.value)}
              className="px-3 py-1.5 bg-gray-50 border border-gray-100 rounded-lg text-[10px] font-bold focus:outline-hidden cursor-pointer"
            >
              <option value="" disabled>Kateqoriya seç</option>
              {categories.map(cat => (
                <option key={cat.id} value={cat.id}>{cat.age} ({cat.weight})</option>
              ))}
            </select>
          </div>

          {selectedCategoryId ? (
            <div className="space-y-4">
              <div className="flex justify-between items-center bg-amber-50/50 border border-amber-100 p-4 rounded-xl">
                <div className="flex items-start gap-2.5">
                  <ShieldAlert className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                  <div className="space-y-1">
                    <p className="text-xs font-bold text-amber-800">Püşkatma Regenerasiyası</p>
                    <p className="text-[9px] text-amber-600 leading-normal">Kateqoriyada iştirakçı sayı dəyişdikdən sonra püşkatmanı yenidən qurmalısınız.</p>
                  </div>
                </div>
                <button
                  onClick={handleGenerateBrackets}
                  className="px-3 py-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg text-[10px] font-bold flex items-center gap-1.5 transition-colors cursor-pointer shrink-0"
                >
                  <RefreshCw className="w-3.5 h-3.5" /> Yenidən Qur
                </button>
              </div>

              {athletesLoading ? (
                <div className="flex items-center justify-center py-6">
                  <div className="w-6 h-6 border-2 border-gray-900 border-t-transparent rounded-full animate-spin"></div>
                </div>
              ) : athletes.length === 0 ? (
                <p className="text-[10px] text-gray-400 text-center py-6">Bu kateqoriyada hələ heç kim qeydiyyatdan keçməyib.</p>
              ) : (
                <div className="bg-gray-50/50 rounded-xl border border-gray-100 overflow-hidden">
                  <table className="w-full text-left text-xs border-collapse">
                    <thead>
                      <tr className="bg-gray-100/50 text-gray-400 font-bold uppercase tracking-wider text-[9px] border-b border-gray-100">
                        <th className="px-3 py-2">Ad Soyad</th>
                        <th className="px-3 py-2">Klub</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100 font-medium text-gray-700 text-[10px]">
                      {athletes.map(ath => (
                        <tr key={ath.id} className="hover:bg-white transition-colors">
                          <td className="px-3 py-2 font-bold text-gray-900">{ath.name}</td>
                          <td className="px-3 py-2">{ath.club} ({ath.country})</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          ) : (
            <p className="text-[10px] text-gray-400 text-center py-12">Rosteri görmək və idarə etmək üçün kateqoriya seçin.</p>
          )}
        </div>

        {/* Column 3: Athlete Quick Register */}
        <div className="bg-white border border-gray-100 rounded-xl p-5 shadow-xs space-y-4 h-fit">
          <div className="flex items-center gap-2 border-b border-gray-50 pb-3">
            <UserPlus className="w-5 h-5 text-gray-500" />
            <h2 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider">İdmançı Əlavə Et</h2>
          </div>

          <form onSubmit={handleRegister} className="space-y-4">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Adı Soyadı</label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Məs. ELMİN HƏSƏNOV"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Klubu</label>
              <input
                type="text"
                required
                value={club}
                onChange={(e) => setClub(e.target.value)}
                placeholder="Məs. Baku Karate Club"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Ölkə</label>
                <input
                  type="text"
                  required
                  value={country}
                  onChange={(e) => setCountry(e.target.value)}
                  placeholder="AZE"
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Kateqoriya</label>
                <select
                  required
                  value={targetCategoryId}
                  onChange={(e) => setTargetCategoryId(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 bg-white rounded-lg text-xs focus:outline-hidden cursor-pointer"
                >
                  <option value="" disabled>Seçin</option>
                  {categories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.age} ({cat.weight})</option>
                  ))}
                </select>
              </div>
            </div>

            <button
              type="submit"
              disabled={regLoading}
              className="w-full py-2.5 bg-gray-900 hover:bg-gray-800 text-white rounded-lg text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer disabled:bg-gray-400"
            >
              {regLoading ? 'Əlavə Edilir...' : 'Rosterə Əlavə Et'}
            </button>
          </form>
        </div>

        {/* Column 4: Add New Category */}
        <div className="bg-white border border-gray-100 rounded-xl p-5 shadow-xs space-y-4 h-fit">
          <div className="flex items-center gap-2 border-b border-gray-50 pb-3">
            <Settings className="w-5 h-5 text-gray-500" />
            <h2 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider">Kateqoriya Əlavə Et</h2>
          </div>

          <form onSubmit={handleAddCategory} className="space-y-4">
            <div>
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Kateqoriya Adı</label>
              <input
                type="text"
                required
                value={catName}
                onChange={(e) => setCatName(e.target.value)}
                placeholder="Məs. 10-11 Yaş (-40 kq) Oğlanlar"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Yaş Qrupu</label>
                <input
                  type="text"
                  required
                  value={catAge}
                  onChange={(e) => setCatAge(e.target.value)}
                  placeholder="Məs. 10-11 Yaş"
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Çəki</label>
                <input
                  type="text"
                  required
                  value={catWeight}
                  onChange={(e) => setCatWeight(e.target.value)}
                  placeholder="Məs. -40 kq"
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-xs focus:outline-hidden focus:ring-1 focus:ring-gray-900"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Cins</label>
                <select
                  required
                  value={catGender}
                  onChange={(e) => setCatGender(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 bg-white rounded-lg text-xs focus:outline-hidden cursor-pointer"
                >
                  <option value="Oğlanlar">Oğlanlar</option>
                  <option value="Qızlar">Qızlar</option>
                </select>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Növ</label>
                <select
                  required
                  value={catType}
                  onChange={(e) => setCatType(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 bg-white rounded-lg text-xs focus:outline-hidden cursor-pointer"
                >
                  <option value="kumite">Kumite</option>
                  <option value="kata">Kata</option>
                </select>
              </div>
            </div>

            <button
              type="submit"
              disabled={catLoading}
              className="w-full py-2.5 bg-gray-900 hover:bg-gray-800 text-white rounded-lg text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer disabled:bg-gray-400 flex items-center justify-center gap-1.5"
            >
              <Save className="w-3.5 h-3.5" /> {catLoading ? 'Əlavə Edilir...' : 'Kateqoriya Yarat'}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
